"""create m1 control plane schema

Revision ID: 92ffcf611555
Revises: 
Create Date: 2026-08-31 06:09:27.236832
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92ffcf611555'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('worker_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('gpu_model', sa.String(length=256), nullable=False),
    sa.Column('vram_mb', sa.Integer(), nullable=False),
    sa.Column('cuda_version', sa.String(length=64), nullable=False),
    sa.Column('worker_version', sa.String(length=64), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('model_versions', sa.JSON(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_worker_devices_positive_capacity')),
    sa.CheckConstraint('vram_mb > 0', name=op.f('ck_worker_devices_positive_vram_mb')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_devices')),
    sa.UniqueConstraint('name', name=op.f('uq_worker_devices_name'))
    )
    op.create_table('upload_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('batch_name', sa.String(length=256), nullable=False),
    sa.Column('source_format', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('manifest_digest', sa.String(length=64), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_size > 0', name=op.f('ck_upload_sessions_positive_chunk_size')),
    sa.CheckConstraint('total_bytes >= 0', name=op.f('ck_upload_sessions_nonnegative_total_bytes')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_upload_sessions_owner_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_sessions'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_digest', sa.LargeBinary(length=32), nullable=False),
    sa.Column('csrf_digest', sa.LargeBinary(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_digest', name=op.f('uq_user_sessions_token_digest'))
    )
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('available_capacity', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.CheckConstraint('available_capacity >= 0', name=op.f('ck_worker_heartbeats_nonnegative_capacity')),
    sa.ForeignKeyConstraint(['device_id'], ['worker_devices.id'], name=op.f('fk_worker_heartbeats_device_id_worker_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_heartbeats'))
    )
    op.create_table('worker_registration_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code_digest', sa.LargeBinary(length=32), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_device_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_worker_registration_codes_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['used_by_device_id'], ['worker_devices.id'], name=op.f('fk_worker_registration_codes_used_by_device_id_worker_devices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_registration_codes')),
    sa.UniqueConstraint('code_digest', name=op.f('uq_worker_registration_codes_code_digest'))
    )
    op.create_table('worker_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('token_digest', sa.LargeBinary(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['worker_devices.id'], name=op.f('fk_worker_tokens_device_id_worker_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_tokens')),
    sa.UniqueConstraint('token_digest', name=op.f('uq_worker_tokens_token_digest'))
    )
    op.create_table('batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_session_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('stage', sa.Enum('registered', 'candidate_ready', 'under_review', 'approved', 'catalog_staged', 'published', 'archived', name='batchstage', native_enum=False), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_format', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('registered', 'candidate_ready', 'under_review', 'approved', 'catalog_staged', 'published', 'archived')", name=op.f('ck_batches_valid_stage')),
    sa.ForeignKeyConstraint(['upload_session_id'], ['upload_sessions.id'], name=op.f('fk_batches_upload_session_id_upload_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    sa.UniqueConstraint('upload_session_id', name=op.f('uq_batches_upload_session_id'))
    )
    op.create_table('upload_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_session_id', sa.Uuid(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('completed_path', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_upload_files_nonnegative_size_bytes')),
    sa.ForeignKeyConstraint(['upload_session_id'], ['upload_sessions.id'], name=op.f('fk_upload_files_upload_session_id_upload_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_files')),
    sa.UniqueConstraint('upload_session_id', 'relative_path', name=op.f('uq_upload_files_upload_session_id'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.String(length=128), nullable=False),
    sa.Column('state', sa.Enum('queued', 'leased', 'running', 'uploading', 'validating', 'succeeded', 'failed', 'cancelled', 'lease_expired', name='jobstate', native_enum=False), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('required_vram_mb', sa.Integer(), nullable=False),
    sa.Column('required_model_version', sa.String(length=128), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('input_manifest', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('queued', 'leased', 'running', 'uploading', 'validating', 'succeeded', 'failed', 'cancelled', 'lease_expired')", name=op.f('ck_jobs_valid_state')),
    sa.CheckConstraint('max_attempts > 0', name=op.f('ck_jobs_positive_max_attempts')),
    sa.CheckConstraint('required_vram_mb >= 0', name=op.f('ck_jobs_nonnegative_vram')),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_jobs_batch_id_batches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_jobs_idempotency_key'))
    )
    op.create_table('source_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_source_groups_batch_id_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_groups')),
    sa.UniqueConstraint('batch_id', 'kind', 'name', name=op.f('uq_source_groups_batch_id'))
    )
    op.create_table('upload_parts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_file_id', sa.Uuid(), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('staging_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('part_number >= 0', name=op.f('ck_upload_parts_nonnegative_part_number')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_upload_parts_nonnegative_size_bytes')),
    sa.ForeignKeyConstraint(['upload_file_id'], ['upload_files.id'], name=op.f('fk_upload_parts_upload_file_id_upload_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_parts')),
    sa.UniqueConstraint('upload_file_id', 'part_number', name=op.f('uq_upload_parts_upload_file_id'))
    )
    op.create_table('images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('source_group_id', sa.Uuid(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('original_relative_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('quality_band', sa.String(length=64), nullable=True),
    sa.Column('relation_note', sa.String(length=128), nullable=True),
    sa.Column('exif_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_images_nonnegative_size_bytes')),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_images_batch_id_batches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_group_id'], ['source_groups.id'], name=op.f('fk_images_source_group_id_source_groups'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images')),
    sa.UniqueConstraint('batch_id', 'source_path', name=op.f('uq_images_batch_id'))
    )
    op.create_table('job_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_device_id', sa.Uuid(), nullable=True),
    sa.Column('lease_token_digest', sa.LargeBinary(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_number > 0', name=op.f('ck_job_attempts_positive_attempt_number')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_attempts_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_device_id'], ['worker_devices.id'], name=op.f('fk_job_attempts_worker_device_id_worker_devices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_attempts')),
    sa.UniqueConstraint('job_id', 'attempt_number', name=op.f('uq_job_attempts_job_id'))
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.String(length=128), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('producer_device_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_artifacts_nonnegative_size_bytes')),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], name=op.f('fk_artifacts_attempt_id_job_attempts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_artifacts_job_id_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producer_device_id'], ['worker_devices.id'], name=op.f('fk_artifacts_producer_device_id_worker_devices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('job_id', 'artifact_type', 'sha256', name=op.f('uq_artifacts_job_id'))
    )
    op.create_table('crops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('crop_index', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('detector_version', sa.String(length=128), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('crop_index >= 0', name=op.f('ck_crops_nonnegative_crop_index')),
    sa.CheckConstraint('width > 0 AND height > 0', name=op.f('ck_crops_positive_dimensions')),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_crops_image_id_images'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crops')),
    sa.UniqueConstraint('image_id', 'crop_index', name=op.f('uq_crops_image_id'))
    )
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], name=op.f('fk_job_events_attempt_id_job_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    op.create_table('job_leases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('lease_token_digest', sa.LargeBinary(length=32), nullable=False),
    sa.Column('leased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], name=op.f('fk_job_leases_attempt_id_job_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['worker_devices.id'], name=op.f('fk_job_leases_device_id_worker_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_leases_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_leases')),
    sa.UniqueConstraint('attempt_id', name=op.f('uq_job_leases_attempt_id')),
    sa.UniqueConstraint('job_id', name=op.f('uq_job_leases_job_id'))
    )
    op.create_table('artifact_manifests',
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('row_binding_digest', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('detector_version', sa.String(length=128), nullable=True),
    sa.Column('preprocess_id', sa.String(length=128), nullable=True),
    sa.Column('pipeline_config_digest', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.CheckConstraint('schema_version > 0', name=op.f('ck_artifact_manifests_positive_schema_version')),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_artifact_manifests_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id', name=op.f('pk_artifact_manifests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifact_manifests')
    op.drop_table('job_leases')
    op.drop_table('job_events')
    op.drop_table('crops')
    op.drop_table('artifacts')
    op.drop_table('job_attempts')
    op.drop_table('images')
    op.drop_table('upload_parts')
    op.drop_table('source_groups')
    op.drop_table('jobs')
    op.drop_table('upload_files')
    op.drop_table('batches')
    op.drop_table('worker_tokens')
    op.drop_table('worker_registration_codes')
    op.drop_table('worker_heartbeats')
    op.drop_table('user_sessions')
    op.drop_table('user_roles')
    op.drop_table('upload_sessions')
    op.drop_table('worker_devices')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###

