"""add confirmed identities and observations

Revision ID: 9d6e7b4ff6ee
Revises: bb659fea583e
Create Date: 2026-08-31 06:18:25.917206
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d6e7b4ff6ee'
down_revision: Union[str, Sequence[str], None] = 'bb659fea583e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmed_individuals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confirmed_individuals')),
    sa.UniqueConstraint('display_name', name=op.f('uq_confirmed_individuals_display_name'))
    )
    op.create_table('identity_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('individual_id', sa.Uuid(), nullable=False),
    sa.Column('review_task_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['individual_id'], ['confirmed_individuals.id'], name=op.f('fk_identity_events_individual_id_confirmed_individuals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_tasks.id'], name=op.f('fk_identity_events_review_task_id_review_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_events')),
    sa.UniqueConstraint('review_task_id', name=op.f('uq_identity_events_review_task_id'))
    )
    op.create_table('individual_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('individual_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['individual_id'], ['confirmed_individuals.id'], name=op.f('fk_individual_aliases_individual_id_confirmed_individuals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_individual_aliases')),
    sa.UniqueConstraint('individual_id', 'alias', 'source', name=op.f('uq_individual_aliases_individual_id'))
    )
    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('individual_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_review_task_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('fk_observations_crop_id_crops'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['individual_id'], ['confirmed_individuals.id'], name=op.f('fk_observations_individual_id_confirmed_individuals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_review_task_id'], ['review_tasks.id'], name=op.f('fk_observations_source_review_task_id_review_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations')),
    sa.UniqueConstraint('crop_id', name=op.f('uq_observations_crop_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('individual_aliases')
    op.drop_table('identity_events')
    op.drop_table('confirmed_individuals')
    # ### end Alembic commands ###

