"""add m2 candidate and review workflow

Revision ID: bb659fea583e
Revises: 92ffcf611555
Create Date: 2026-08-31 06:13:22.949416
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb659fea583e'
down_revision: Union[str, Sequence[str], None] = '92ffcf611555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('required_reviewers', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('required_reviewers > 0', name=op.f('ck_review_tasks_positive_reviewers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_tasks'))
    )
    op.create_table('review_conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['review_tasks.id'], name=op.f('fk_review_conflicts_task_id_review_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_conflicts')),
    sa.UniqueConstraint('task_id', name=op.f('uq_review_conflicts_task_id'))
    )
    op.create_table('review_consensus',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('conclusion', sa.String(length=64), nullable=True),
    sa.Column('individual_id', sa.Uuid(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['review_tasks.id'], name=op.f('fk_review_consensus_task_id_review_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_review_consensus'))
    )
    op.create_table('review_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('revision > 0', name=op.f('ck_review_events_positive_revision')),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], name=op.f('fk_review_events_reviewer_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['review_tasks.id'], name=op.f('fk_review_events_task_id_review_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_events')),
    sa.UniqueConstraint('task_id', 'reviewer_user_id', 'revision', name=op.f('uq_review_events_task_id'))
    )
    op.create_table('reviewer_rosters',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], name=op.f('fk_reviewer_rosters_reviewer_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['review_tasks.id'], name=op.f('fk_reviewer_rosters_task_id_review_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'reviewer_user_id', name=op.f('pk_reviewer_rosters'))
    )
    op.create_table('candidate_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('algorithm', sa.String(length=128), nullable=False),
    sa.Column('algorithm_version', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('representative_crop_id', sa.Uuid(), nullable=True),
    sa.Column('provenance_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_candidate_clusters_batch_id_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_artifact_id'], ['artifacts.id'], name=op.f('fk_candidate_clusters_provenance_artifact_id_artifacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['representative_crop_id'], ['crops.id'], name=op.f('fk_candidate_clusters_representative_crop_id_crops'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_clusters')),
    sa.UniqueConstraint('batch_id', 'label', name=op.f('uq_candidate_clusters_batch_id'))
    )
    op.create_table('candidate_cluster_members',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('membership_score', sa.Float(), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['candidate_clusters.id'], name=op.f('fk_candidate_cluster_members_cluster_id_candidate_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('fk_candidate_cluster_members_crop_id_crops'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cluster_id', 'crop_id', name=op.f('pk_candidate_cluster_members'))
    )
    op.create_table('candidate_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_candidate_events_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cluster_id'], ['candidate_clusters.id'], name=op.f('fk_candidate_events_cluster_id_candidate_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_events')
    op.drop_table('candidate_cluster_members')
    op.drop_table('candidate_clusters')
    op.drop_table('reviewer_rosters')
    op.drop_table('review_events')
    op.drop_table('review_consensus')
    op.drop_table('review_conflicts')
    op.drop_table('review_tasks')
    # ### end Alembic commands ###

